# Generated by Django 2.2.4 on 2020-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=6, unique=True)),
                ('full_url', models.URLField()),
                ('visited_total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'url',
            },
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['full_url'], name='full_url_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['created_at'], name='created_at_idx'),
        ),
    ]
