# Generated by Django 2.2.4 on 2020-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compress', '0002_auto_20200511_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='visited_total_count',
            field=models.IntegerField(default=0),
        ),
    ]
