# Generated by Django 2.2.4 on 2020-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_hour', models.IntegerField()),
                ('url_id', models.IntegerField()),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
