# Generated by Django 2.2.4 on 2020-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_hour', models.IntegerField()),
                ('slug', models.CharField(max_length=6)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['created_date', 'created_hour'], name='date_hour_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['created_date'], name='date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('created_date', 'created_hour', 'slug')},
        ),
    ]
