# Generated by Django 2.2.4 on 2020-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'slug',
            },
        ),
    ]
