# Generated by Django 2.2.4 on 2020-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluggen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slug',
            name='slug',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
